CREATE TABLE IF NOT EXISTS review_api_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       VARCHAR(36) NOT NULL UNIQUE,
    idempotency_key VARCHAR(128) NOT NULL UNIQUE,
    review_task_id  BIGINT NOT NULL,
    review_run_id   BIGINT NOT NULL,
    status          VARCHAR(32) NOT NULL,
    error_code      VARCHAR(64),
    error_message   VARCHAR(1000),
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_api_task FOREIGN KEY (review_task_id) REFERENCES review_task(id),
    CONSTRAINT fk_review_api_run FOREIGN KEY (review_run_id) REFERENCES review_run(id)
);
CREATE INDEX IF NOT EXISTS idx_review_api_status ON review_api_run(status, updated_at);

CREATE TABLE IF NOT EXISTS review_api_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id BIGINT NOT NULL,
    sequence_number BIGINT NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    status          VARCHAR(32) NOT NULL,
    summary         VARCHAR(2000),
    error_code      VARCHAR(64),
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_api_event_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id),
    CONSTRAINT uk_review_api_event_sequence UNIQUE(review_api_run_id, sequence_number)
);
CREATE INDEX IF NOT EXISTS idx_review_api_event_replay ON review_api_event(review_api_run_id, sequence_number);
