-- Fresh-database cutover: ReviewApiRun is the only review aggregate root.
-- Existing installations are intentionally not migrated; back up and recreate them for v1.

DROP TABLE IF EXISTS review_api_event CASCADE;
DROP TABLE IF EXISTS review_api_run CASCADE;
DROP TABLE IF EXISTS rag_retrieval_trace CASCADE;
DROP TABLE IF EXISTS review_issue_evidence CASCADE;
DROP TABLE IF EXISTS review_comment_preview CASCADE;
DROP TABLE IF EXISTS review_provider_trace CASCADE;
DROP TABLE IF EXISTS review_tool_trace CASCADE;
DROP TABLE IF EXISTS review_input_snapshot CASCADE;
DROP TABLE IF EXISTS review_issue CASCADE;
DROP TABLE IF EXISTS review_run CASCADE;
DROP TABLE IF EXISTS review_task CASCADE;

CREATE TABLE review_api_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           VARCHAR(36) NOT NULL UNIQUE,
    idempotency_key     VARCHAR(128) NOT NULL UNIQUE,
    repo_url            VARCHAR(500) NOT NULL,
    pr_number           INT NOT NULL,
    diff_text           TEXT,
    status              VARCHAR(32) NOT NULL,
    summary             VARCHAR(1000),
    requested_provider  VARCHAR(32),
    provider_used       VARCHAR(32),
    provider_hit        BOOLEAN,
    review_mode         VARCHAR(32) NOT NULL,
    run_number          INT NOT NULL,
    execution_status    VARCHAR(32) NOT NULL,
    error_code          VARCHAR(64),
    error_message       VARCHAR(1000),
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL
);
CREATE INDEX idx_review_api_run_status ON review_api_run(status, updated_at);

CREATE TABLE review_api_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    sequence_number     BIGINT NOT NULL,
    event_type          VARCHAR(64) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    summary             VARCHAR(2000),
    error_code          VARCHAR(64),
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_api_event_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE,
    CONSTRAINT uk_review_api_event_sequence UNIQUE(review_api_run_id, sequence_number)
);

CREATE TABLE review_issue (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    issue_key           VARCHAR(255) NOT NULL,
    severity            VARCHAR(32) NOT NULL,
    category            VARCHAR(32) NOT NULL,
    source              VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    file_path           VARCHAR(500) NOT NULL,
    start_line          INT NOT NULL,
    end_line            INT,
    title               VARCHAR(500) NOT NULL,
    description         VARCHAR(2000) NOT NULL,
    recommendation      VARCHAR(2000) NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_issue_api_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE
);
CREATE INDEX idx_review_issue_api_run_id ON review_issue(review_api_run_id);

CREATE TABLE review_input_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    repo_url            VARCHAR(500) NOT NULL,
    owner               VARCHAR(128),
    repo                VARCHAR(128),
    pr_number           INT NOT NULL,
    base_ref            VARCHAR(255),
    head_ref            VARCHAR(255),
    base_sha            VARCHAR(64),
    head_sha            VARCHAR(64),
    pr_title            VARCHAR(500),
    pr_author           VARCHAR(255),
    changed_files       INT,
    additions           INT,
    deletions           INT,
    diff_truncated      BOOLEAN NOT NULL DEFAULT FALSE,
    context_truncated   BOOLEAN NOT NULL DEFAULT FALSE,
    snapshot_json       TEXT NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_input_snapshot_api_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE
);

CREATE TABLE review_tool_trace (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    sequence_number     INT NOT NULL,
    tool_name           VARCHAR(128) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    input_summary       VARCHAR(1000),
    output_summary      VARCHAR(2000),
    output_ref          VARCHAR(255),
    error_code          VARCHAR(64),
    error_message       VARCHAR(1000),
    started_at          TIMESTAMP NOT NULL,
    finished_at         TIMESTAMP,
    duration_ms         BIGINT,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_tool_trace_api_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE
);

CREATE TABLE review_provider_trace (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    requested_provider  VARCHAR(32),
    provider_used       VARCHAR(32),
    provider_hit        BOOLEAN,
    model_name          VARCHAR(128),
    input_summary       VARCHAR(1000),
    output_summary      VARCHAR(2000),
    finding_count       INT,
    normalization_summary VARCHAR(1000),
    fallback_reason     VARCHAR(1000),
    started_at          TIMESTAMP NOT NULL,
    finished_at         TIMESTAMP,
    duration_ms         BIGINT,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_provider_trace_api_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE
);

CREATE TABLE review_comment_preview (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    review_issue_id     BIGINT,
    issue_key           VARCHAR(255),
    file_path           VARCHAR(500) NOT NULL,
    line_number         INT,
    side                VARCHAR(16),
    draft_body          VARCHAR(4000) NOT NULL,
    severity            VARCHAR(16),
    category            VARCHAR(32),
    source              VARCHAR(32),
    selected_for_publish BOOLEAN NOT NULL DEFAULT FALSE,
    publish_status      VARCHAR(32) NOT NULL DEFAULT 'NOT_PUBLISHED',
    github_comment_id   BIGINT,
    github_comment_url  VARCHAR(1000),
    publish_error_message VARCHAR(1000),
    published_at        TIMESTAMP,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_comment_preview_api_run FOREIGN KEY (review_api_run_id) REFERENCES review_api_run(id) ON DELETE CASCADE
);

CREATE TABLE review_issue_evidence (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_issue_id     BIGINT NOT NULL,
    rag_chunk_id        BIGINT,
    citation_label      VARCHAR(32) NOT NULL,
    path                VARCHAR(1000) NOT NULL,
    start_line          INT NOT NULL,
    end_line            INT NOT NULL,
    content_hash        VARCHAR(64) NOT NULL,
    evidence_excerpt    VARCHAR(2000) NOT NULL,
    retrieval_rank      INT NOT NULL,
    retrieval_score     DOUBLE PRECISION NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_issue_evidence_issue FOREIGN KEY (review_issue_id) REFERENCES review_issue(id) ON DELETE CASCADE,
    CONSTRAINT uq_review_issue_evidence_issue_citation UNIQUE (review_issue_id, citation_label)
);

CREATE TABLE rag_retrieval_trace (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_api_run_id   BIGINT NOT NULL,
    repository_id       BIGINT NOT NULL,
    commit_sha          VARCHAR(64) NOT NULL,
    query_hash          VARCHAR(64) NOT NULL,
    vector_candidate_count INT NOT NULL,
    lexical_candidate_count INT NOT NULL,
    reranked_count      INT NOT NULL,
    selected_count      INT NOT NULL,
    context_char_count  INT NOT NULL,
    degraded            BOOLEAN NOT NULL,
    latency_ms          BIGINT NOT NULL,
    result_summary_json TEXT NOT NULL,
    created_at          TIMESTAMP NOT NULL
);
