CREATE TABLE github_installation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id BIGINT NOT NULL UNIQUE,
    account_login VARCHAR(255) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE github_installation_repository (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_installation_id BIGINT NOT NULL,
    repository_owner VARCHAR(255) NOT NULL,
    repository_name VARCHAR(255) NOT NULL,
    github_repository_id BIGINT,
    status VARCHAR(32) NOT NULL,
    last_verified_at TIMESTAMP,
    CONSTRAINT fk_github_installation_repository_installation
        FOREIGN KEY (github_installation_id) REFERENCES github_installation(id) ON DELETE CASCADE,
    CONSTRAINT uq_github_installation_repository UNIQUE (github_installation_id, repository_owner, repository_name)
);

ALTER TABLE review_api_run ADD COLUMN github_credential_mode VARCHAR(32);
ALTER TABLE review_api_run ADD COLUMN github_installation_id BIGINT;
ALTER TABLE review_api_run ADD COLUMN github_repository_id BIGINT;
