-- Baseline schema matching Stage 1.5 review_task and review_issue entities.

CREATE TABLE IF NOT EXISTS review_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_url            VARCHAR(500)  NOT NULL,
    pr_number           INT           NOT NULL,
    diff_text           CLOB,
    status              VARCHAR(32)   NOT NULL,
    summary             VARCHAR(1000),
    requested_provider  VARCHAR(16),
    provider_used       VARCHAR(16),
    provider_hit        BOOLEAN,
    error_message       VARCHAR(2000),
    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_review_task_created_at ON review_task (created_at);

CREATE TABLE IF NOT EXISTS review_issue (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_task_id  BIGINT        NOT NULL,
    issue_key       VARCHAR(255)  NOT NULL,
    severity        VARCHAR(32)   NOT NULL,
    category        VARCHAR(32)   NOT NULL,
    source          VARCHAR(32)   NOT NULL,
    status          VARCHAR(32)   NOT NULL,
    file_path       VARCHAR(500)  NOT NULL,
    start_line      INT           NOT NULL,
    end_line        INT,
    title           VARCHAR(500)  NOT NULL,
    description     VARCHAR(2000) NOT NULL,
    recommendation  VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_review_issue_task FOREIGN KEY (review_task_id) REFERENCES review_task (id)
);

CREATE INDEX IF NOT EXISTS idx_review_issue_task_id ON review_issue (review_task_id);
