-- Stage 2 run, trace, snapshot, and comment preview tables.

CREATE TABLE IF NOT EXISTS review_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_task_id      BIGINT        NOT NULL,
    run_number          INT           NOT NULL,
    review_mode         VARCHAR(32)   NOT NULL,
    status              VARCHAR(32)   NOT NULL,
    requested_provider  VARCHAR(32),
    provider_used       VARCHAR(32),
    provider_hit        BOOLEAN,
    error_code          VARCHAR(64),
    error_message       VARCHAR(1000),
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL,
    CONSTRAINT fk_review_run_task FOREIGN KEY (review_task_id) REFERENCES review_task (id),
    CONSTRAINT uq_review_run_task_number UNIQUE (review_task_id, run_number)
);

CREATE INDEX IF NOT EXISTS idx_review_run_task_id ON review_run (review_task_id);
CREATE INDEX IF NOT EXISTS idx_review_run_status ON review_run (status);
CREATE INDEX IF NOT EXISTS idx_review_run_created_at ON review_run (created_at);

CREATE TABLE IF NOT EXISTS review_input_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id       BIGINT        NOT NULL,
    repo_url            VARCHAR(500)  NOT NULL,
    owner               VARCHAR(128),
    repo                VARCHAR(128),
    pr_number           INT           NOT NULL,
    base_ref            VARCHAR(255),
    head_ref            VARCHAR(255),
    base_sha            VARCHAR(64),
    head_sha            VARCHAR(64),
    pr_title            VARCHAR(500),
    pr_author           VARCHAR(255),
    changed_files       INT,
    additions           INT,
    deletions           INT,
    diff_truncated      BOOLEAN       NOT NULL DEFAULT FALSE,
    context_truncated   BOOLEAN       NOT NULL DEFAULT FALSE,
    snapshot_json       CLOB          NOT NULL,
    created_at          TIMESTAMP     NOT NULL,
    CONSTRAINT fk_input_snapshot_run FOREIGN KEY (review_run_id) REFERENCES review_run (id)
);

CREATE INDEX IF NOT EXISTS idx_input_snapshot_run_id ON review_input_snapshot (review_run_id);

CREATE TABLE IF NOT EXISTS review_tool_trace (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id       BIGINT        NOT NULL,
    sequence_number     INT           NOT NULL,
    tool_name           VARCHAR(128)  NOT NULL,
    status              VARCHAR(32)   NOT NULL,
    input_summary       VARCHAR(1000),
    output_summary      VARCHAR(2000),
    output_ref          VARCHAR(255),
    error_code          VARCHAR(64),
    error_message       VARCHAR(1000),
    started_at          TIMESTAMP     NOT NULL,
    finished_at         TIMESTAMP,
    duration_ms         BIGINT,
    created_at          TIMESTAMP     NOT NULL,
    CONSTRAINT fk_tool_trace_run FOREIGN KEY (review_run_id) REFERENCES review_run (id)
);

CREATE INDEX IF NOT EXISTS idx_tool_trace_run_sequence ON review_tool_trace (review_run_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_tool_trace_tool_name ON review_tool_trace (tool_name);
CREATE INDEX IF NOT EXISTS idx_tool_trace_status ON review_tool_trace (status);

CREATE TABLE IF NOT EXISTS review_provider_trace (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id           BIGINT        NOT NULL,
    requested_provider      VARCHAR(32),
    provider_used           VARCHAR(32),
    provider_hit            BOOLEAN,
    model_name              VARCHAR(128),
    input_summary           VARCHAR(1000),
    output_summary          VARCHAR(2000),
    finding_count           INT,
    normalization_summary   VARCHAR(1000),
    fallback_reason         VARCHAR(1000),
    started_at              TIMESTAMP     NOT NULL,
    finished_at             TIMESTAMP,
    duration_ms             BIGINT,
    created_at              TIMESTAMP     NOT NULL,
    CONSTRAINT fk_provider_trace_run FOREIGN KEY (review_run_id) REFERENCES review_run (id)
);

CREATE INDEX IF NOT EXISTS idx_provider_trace_run_id ON review_provider_trace (review_run_id);

CREATE TABLE IF NOT EXISTS review_comment_preview (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id           BIGINT        NOT NULL,
    review_issue_id         BIGINT,
    issue_key               VARCHAR(255),
    file_path               VARCHAR(500)  NOT NULL,
    line_number             INT,
    side                    VARCHAR(16),
    draft_body              VARCHAR(4000) NOT NULL,
    severity                VARCHAR(16),
    category                VARCHAR(32),
    source                  VARCHAR(32),
    selected_for_publish    BOOLEAN       NOT NULL DEFAULT FALSE,
    publish_status          VARCHAR(32)   NOT NULL DEFAULT 'NOT_PUBLISHED',
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL,
    CONSTRAINT fk_comment_preview_run FOREIGN KEY (review_run_id) REFERENCES review_run (id)
);

CREATE INDEX IF NOT EXISTS idx_comment_preview_run_id ON review_comment_preview (review_run_id);

ALTER TABLE review_task ADD COLUMN IF NOT EXISTS review_mode VARCHAR(32);
ALTER TABLE review_task ADD COLUMN IF NOT EXISTS latest_run_id BIGINT;

ALTER TABLE review_issue ADD COLUMN IF NOT EXISTS review_run_id BIGINT;
