CREATE TABLE IF NOT EXISTS demo_run (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               VARCHAR(36)   NOT NULL UNIQUE,
    scenario_id             VARCHAR(64)   NOT NULL,
    idempotency_key         VARCHAR(64)   NOT NULL UNIQUE,
    requester_ip_hash       VARCHAR(64)   NOT NULL,
    review_task_id          BIGINT        NOT NULL,
    review_run_id           BIGINT        NOT NULL,
    status                  VARCHAR(32)   NOT NULL,
    decision                VARCHAR(32),
    replay_reason           VARCHAR(1000),
    safe_diff_text          CLOB,
    published_comment_url   VARCHAR(1000),
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL,
    finished_at             TIMESTAMP,
    CONSTRAINT fk_demo_task FOREIGN KEY (review_task_id) REFERENCES review_task (id),
    CONSTRAINT fk_demo_review_run FOREIGN KEY (review_run_id) REFERENCES review_run (id)
);

CREATE INDEX IF NOT EXISTS idx_demo_run_review_run ON demo_run (review_run_id);
CREATE INDEX IF NOT EXISTS idx_demo_run_status ON demo_run (status);
CREATE INDEX IF NOT EXISTS idx_demo_run_requester ON demo_run (requester_ip_hash, status);

CREATE TABLE IF NOT EXISTS review_execution_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_run_id         BIGINT        NOT NULL UNIQUE,
    status              VARCHAR(32)   NOT NULL,
    attempt_count       INT           NOT NULL DEFAULT 0,
    lease_owner         VARCHAR(128),
    heartbeat_at        TIMESTAMP,
    lease_expires_at    TIMESTAMP,
    next_retry_at       TIMESTAMP,
    error_code          VARCHAR(64),
    error_message       VARCHAR(1000),
    created_at          TIMESTAMP     NOT NULL,
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    CONSTRAINT fk_execution_job_demo FOREIGN KEY (demo_run_id) REFERENCES demo_run (id)
);

CREATE INDEX IF NOT EXISTS idx_execution_job_claim
    ON review_execution_job (status, next_retry_at, lease_expires_at);

CREATE TABLE IF NOT EXISTS review_run_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_run_id         BIGINT        NOT NULL,
    sequence_number     BIGINT        NOT NULL,
    event_type          VARCHAR(64)   NOT NULL,
    step                VARCHAR(64),
    status              VARCHAR(32)   NOT NULL,
    summary             VARCHAR(2000),
    error_code          VARCHAR(64),
    duration_ms         BIGINT,
    created_at          TIMESTAMP     NOT NULL,
    CONSTRAINT fk_run_event_demo FOREIGN KEY (demo_run_id) REFERENCES demo_run (id),
    CONSTRAINT uk_run_event_sequence UNIQUE (demo_run_id, sequence_number)
);

CREATE INDEX IF NOT EXISTS idx_run_event_replay
    ON review_run_event (demo_run_id, sequence_number);

CREATE TABLE IF NOT EXISTS demo_request_bucket (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash             VARCHAR(64)   NOT NULL,
    window_start        TIMESTAMP     NOT NULL,
    request_count       INT           NOT NULL,
    updated_at          TIMESTAMP     NOT NULL,
    CONSTRAINT uk_demo_request_bucket UNIQUE (ip_hash, window_start)
);

ALTER TABLE review_comment_preview ADD COLUMN IF NOT EXISTS github_comment_url VARCHAR(1000);
