package com.codereviewx.backend.review.service;

import com.codereviewx.backend.rag.indexing.RagIndexWorker;
import com.codereviewx.backend.rag.persistence.ReviewIssueEvidenceStore;
import com.codereviewx.backend.rag.retrieval.RagRetrievalService;
import com.codereviewx.backend.rag.retrieval.RerankClient;
import com.codereviewx.backend.rag.service.RagIndexService;
import com.codereviewx.backend.rag.service.RagManifestSnapshotReader;
import com.codereviewx.backend.review.github.GithubPrDiffLoader;
import com.codereviewx.backend.review.github.GithubPrMetadataLoader;
import com.codereviewx.backend.review.persistence.repository.ReviewCommentPreviewRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewInputSnapshotRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewIssueRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewProviderTraceRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewRunRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewTaskRepository;
import com.codereviewx.backend.review.persistence.repository.ReviewToolTraceRepository;
import com.codereviewx.backend.review.pipeline.provider.mimo.XiaomiMiMoClient;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@Tag("postgres")
@TestPropertySource(properties = {
        "codereviewx.github.token=test-token",
        "codereviewx.rag.enabled=true",
        "codereviewx.rag.review-percentage=100",
        "codereviewx.rag.fallback-enabled=false",
        "codereviewx.rag.embedding-base-url=http://127.0.0.1/embedding",
        "codereviewx.rag.embedding-api-key=test-embedding-key",
        "codereviewx.rag.rerank-base-url=http://127.0.0.1/rerank",
        "codereviewx.rag.rerank-api-key=test-rerank-key"
})
class RagFindingQualityAcceptanceTest {

    @Autowired private ReviewTaskService service;
    @Autowired private ReviewToolTraceRepository toolTraceRepository;
    @Autowired private ReviewCommentPreviewRepository previewRepository;
    @Autowired private ReviewProviderTraceRepository providerTraceRepository;
    @Autowired private ReviewInputSnapshotRepository snapshotRepository;
    @Autowired private ReviewRunRepository runRepository;
    @Autowired private ReviewIssueRepository issueRepository;
    @Autowired private ReviewTaskRepository taskRepository;
    @Autowired private JdbcTemplate jdbcTemplate;
    @Autowired private ObjectMapper objectMapper;
    @MockBean private GithubPrMetadataLoader metadataLoader;
    @MockBean private GithubPrDiffLoader diffLoader;
    @MockBean private XiaomiMiMoClient mimoClient;
    @MockBean private RagIndexService ragIndexService;
    @MockBean private RagManifestSnapshotReader manifestSnapshotReader;
    @MockBean private RagRetrievalService retrievalService;
    @MockBean private RerankClient rerankClient;
    @MockBean private ReviewIssueEvidenceStore evidenceStore;
    @MockBean private RagIndexWorker ragIndexWorker;

    @BeforeEach
    void clean() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS rag_retrieval_trace (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    review_run_id BIGINT NOT NULL,
                    repository_id BIGINT NOT NULL,
                    commit_sha VARCHAR(64) NOT NULL,
                    query_hash VARCHAR(64) NOT NULL,
                    vector_candidate_count INT NOT NULL,
                    lexical_candidate_count INT NOT NULL,
                    reranked_count INT NOT NULL,
                    selected_count INT NOT NULL,
                    context_char_count INT NOT NULL,
                    degraded BOOLEAN NOT NULL,
                    latency_ms BIGINT NOT NULL,
                    result_summary_json TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL
                )
                """);
        previewRepository.deleteAll();
        toolTraceRepository.deleteAll();
        providerTraceRepository.deleteAll();
        snapshotRepository.deleteAll();
        runRepository.deleteAll();
        issueRepository.deleteAll();
        taskRepository.deleteAll();
    }

    @Test
    void productionReviewPipelineMeetsCommittedFindingAndEvidenceGate() throws Exception {
        RagFindingProductionEvaluation.Result result = evaluation().run(
                RagFindingProductionEvaluation.Mutation.NONE, true);

        assertThat(result.metrics().failures()).isEmpty();
        assertThat(result.metrics().evidenceValidationPassRate()).isGreaterThanOrEqualTo(0.95);
        assertThat(result.metrics().groundedFindingPrecision()).isEqualTo(1.0);
        assertThat(result.metrics().expectedFindingPassRate()).isEqualTo(1.0);
        assertThat(result.jsonReport()).exists();
        assertThat(result.markdownReport()).exists();
        JsonNode report = objectMapper.readTree(result.jsonReport().toFile());
        assertThat(report.path("engine").asText()).isEqualTo("java-production-review-pipeline");
        assertThat(report.path("status").asText()).isEqualTo("PASS");
        assertThat(report.path("cases")).hasSize(5);
    }

    @Test
    void productionGateRejectsEvidenceAndGroundingMutations() throws Exception {
        for (RagFindingProductionEvaluation.Mutation mutation : List.of(
                RagFindingProductionEvaluation.Mutation.MISSING_EVIDENCE,
                RagFindingProductionEvaluation.Mutation.WRONG_CHUNK,
                RagFindingProductionEvaluation.Mutation.WRONG_PATH,
                RagFindingProductionEvaluation.Mutation.WRONG_COMMIT,
                RagFindingProductionEvaluation.Mutation.UNGROUNDED_FINDING)) {
            RagFindingQualityMetrics metrics = evaluation().run(mutation, false).metrics();
            assertThat(metrics.failures()).as(mutation.name()).isNotEmpty();
            assertThat(metrics.failures()).as(mutation.name()).contains("expectedFindingPassRate");
            if (mutation == RagFindingProductionEvaluation.Mutation.MISSING_EVIDENCE
                    || mutation == RagFindingProductionEvaluation.Mutation.WRONG_PATH
                    || mutation == RagFindingProductionEvaluation.Mutation.UNGROUNDED_FINDING) {
                assertThat(metrics.failures()).as(mutation.name()).contains("evidenceValidationPassRate");
            }
            assertThat(metrics.failures()).as(mutation.name()).contains("groundedFindingPrecision");
        }
    }

    private RagFindingProductionEvaluation evaluation() {
        return new RagFindingProductionEvaluation(service, metadataLoader, diffLoader, mimoClient,
                ragIndexService, manifestSnapshotReader, retrievalService, rerankClient, evidenceStore,
                objectMapper);
    }
}
