ALTER TABLE rag_index_job ADD COLUMN IF NOT EXISTS phase VARCHAR(32) NOT NULL DEFAULT 'QUEUED';
ALTER TABLE rag_index_job ADD COLUMN IF NOT EXISTS total_file_count INT NOT NULL DEFAULT 0;
ALTER TABLE rag_index_job ADD COLUMN IF NOT EXISTS last_progress_at TIMESTAMP;
ALTER TABLE rag_index_job ADD COLUMN IF NOT EXISTS deadline_at TIMESTAMP;
